### ISSUE TITLE
weird issue when joining server(1.12.2)Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by SDUBZ** [TheLMiffy1111/DummyCoreUnofficial#2]
as mentioned here https://github.com/grim3212/grim-pack/issues/114#issuecomment-354700022

using
 EssentialCraftUnofficial-4.8.112.3 and DummyCoreUnofficial-2.4.112.0

**Comment by SDUBZ** [comment]
also error when building events 
shown here : https://puu.sh/yT53D/28776ca2e0.log @TheLMiffy1111 
  starts at line 5155
  this is testing with dummycore DummyCoreUnofficial-2.4.112.1

**Comment by SDUBZ** [comment]
https://pastebin.com/iMnDd0MF this is the printout mentioning nullpointer exceptions
  Forge:1.12.2-2582
ec4: EssentialCraftUnofficial-4.8.112.3
dcu: DummyCoreUnofficial-2.4.112.1

**Comment by SDUBZ** [comment]
gonna try new essentialcraft: EssentialCraftUnofficial-4.8.112.4

**Comment by SDUBZ** [comment]
the pastebin i mentioned earlier is still hapening
with 
Forge:1.12.2-2582
ec4: EssentialCraftUnofficial-4.8.112.4
dcu: DummyCoreUnofficial-2.4.112.1

tobe noted: i can join the server atleast now but those printouts are still happening

**Comment by SDUBZ** [comment]
from what i see in the logs your not sending packets correctly, have you tried running a virtual server to try troubleshooting the core and mods?
alsop if you need anymore recent logs to try and nail down the issue just let me know

**Comment by TheLMiffy1111** [comment]
This is an EssentialCraft issue.
It will be fixed in the next update.
